uploads = []

[[generated]]
id = "BCvp7YM_cMtmnPY4lWHT4"
uri = "file://artifacts/mobile-app/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "BjaxbsRsUWVkAFbJhasC_"
uri = "file://.local/outputs/Learner-Log-Pitch-Deck.pptx"
type = "slides"
title = "Learner Log Pitch Deck (PPTX)"
