import { Router, type IRouter } from "express";
import healthRouter from "./health";
import clearSessionRouter from "./clear-session";
import usersRouter from "./users";
import studentsRouter from "./students";
import instructorsRouter from "./instructors";
import maneuversRouter from "./maneuvers";
import assessmentsRouter from "./assessments";
import handoverRouter from "./handover";
import intakeRouter from "./intake";
import dashboardRouter from "./dashboard";
import auditRouter from "./audit";
import availabilityRouter from "./availability";
import zonesRouter from "./zones";
import bookingsRouter from "./bookings";
import notificationsRouter from "./notifications";
import lessonPlanRouter from "./lesson-plan";
import storageRouter from "./storage";
import verificationRouter from "./verification";
import termsRouter from "./terms";
import moderationRouter from "./moderation";
import schoolsRouter from "./schools";
import viewerLinksRouter from "./viewer-links";
import billingRouter from "./billing";
import demoRouter from "./demo";
import bookingApprovalsRouter from "./booking-approvals";

const router: IRouter = Router();

router.use(healthRouter);
router.use(clearSessionRouter);
router.use(usersRouter);
router.use(studentsRouter);
router.use(instructorsRouter);
router.use(maneuversRouter);
router.use(assessmentsRouter);
router.use(handoverRouter);
router.use(intakeRouter);
router.use(dashboardRouter);
router.use(auditRouter);
router.use(availabilityRouter);
router.use(zonesRouter);
router.use(bookingsRouter);
router.use(notificationsRouter);
router.use(lessonPlanRouter);
router.use(storageRouter);
router.use(verificationRouter);
router.use(termsRouter);
router.use(moderationRouter);
router.use(schoolsRouter);
router.use(viewerLinksRouter);
router.use(billingRouter);
router.use(demoRouter);
router.use(bookingApprovalsRouter);

export default router;
